### ISSUE TITLE
lumia920无法解锁

### ISSUE THREAD

**Issue by Remedgit** [chengcong/shuajimi#5]
设备是lumia920at&t版白色
解锁log
Windows Phone Internals version 2.9.7854.34378
Copyright Heathcliff74 / wpinternals.net
Command: Unlock Bootloader V1
Connected device: Lumia
Mode: Flash
Phone name: Nokia.MSM8960.P4301.3.2.1
Root key hash: 00E9427DF118D9E27D098D13BECB6C6C89CE59F4ECCF5549C49BC0DB952A6BB4
Flash app: 2.2
Flash protocol: 1.18
SecureBoot: Enabled (Platform Secure Boot: Enabled, UEFI Secure Boot: Enabled)
Flash app security: Enabled
JTAG: Disabled
Assembling data for unlock
Rebooting phone
Lumia disconnected
Connected device: Lumia
Mode: Bootloader
Rebooting phone to Flash mode
Lumia disconnected
Connected device: Lumia
Mode: Flash
Error: Flash failed!
Error 0x1304: Invalid platform ID
使用WPI出现Flashfaild

**Comment by chengcong** [comment]
你是不是在大容量模式下删分区或者格式化分区了？




熊猫大王
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chengcong/shuajimi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月17日(星期六) 下午2:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chengcong/shuajimi] lumia920无法解锁 (Issue #5)





 
设备是lumia920at&amp;t版白色
 解锁log
 Windows Phone Internals version 2.9.7854.34378
 Copyright Heathcliff74 / wpinternals.net
 Command: Unlock Bootloader V1
 Connected device: Lumia
 Mode: Flash
 Phone name: Nokia.MSM8960.P4301.3.2.1
 Root key hash: 00E9427DF118D9E27D098D13BECB6C6C89CE59F4ECCF5549C49BC0DB952A6BB4
 Flash app: 2.2
 Flash protocol: 1.18
 SecureBoot: Enabled (Platform Secure Boot: Enabled, UEFI Secure Boot: Enabled)
 Flash app security: Enabled
 JTAG: Disabled
 Assembling data for unlock
 Rebooting phone
 Lumia disconnected
 Connected device: Lumia
 Mode: Bootloader
 Rebooting phone to Flash mode
 Lumia disconnected
 Connected device: Lumia
 Mode: Flash
 Error: Flash failed!
 Error 0x1304: Invalid platform ID
 使用WPI出现Flashfaild

**Comment by Remedgit** [comment]
没有解锁过设备的

**Comment by Remedgit** [comment]
自然没有进入过大容量模式

**Comment by Remedgit** [comment]
在wp8和wp10同情况

**Comment by chengcong** [comment]
platform id 坏了，基本是没救了。哪里买的，搞不好买来就是坏的




熊猫大王
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chengcong/shuajimi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月17日(星期六) 下午3:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chengcong/shuajimi] lumia920无法解锁 (Issue #5)





 
没有解锁过设备的
